USE metadash;

DROP TABLE IF EXISTS data_source;
CREATE TABLE IF NOT EXISTS data_source (
data_source_abbrev VARCHAR (20) NULL, 
data_source_name VARCHAR (250) NOT NULL, 
data_source_url VARCHAR (400) NULL, 
description VARCHAR (800) NULL, 
restricted BIT NULL,
terms_of_use VARCHAR(500) NULL,
nmfldfordatsrc BIGINT (4) NULL, 
contracts VARCHAR (200) NULL, 
date_created DATETIME NULL, 
creator VARCHAR (20) NULL, 
last_updated DATETIME NULL, 
update_user VARCHAR (20) NULL, 
exclude BIT NULL, 
delete_row BIT NULL,
rowsource varchar(12) NULL, 
hubid CHAR (10) NULL, 
orgid CHAR(10) NULL,
projid CHAR(10) NULL,
comments VARCHAR (600) NULL,
id BIGINT (4) NOT NULL AUTO_INCREMENT, PRIMARY KEY (ID) );

/* 'CDPH', 'CPD', 'CPS', 'COOK_DPH', 'COOK_JUVCT', 'IDES', 'IL_DCFS', 'IL_HFS', 'IL_DJJ', 'IL_DHS', 'IL_DPH', 'NSC', 'GTS'  */

INSERT INTO data_source (data_source_abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) 
VALUES('CDPH','Chicago Department of Public Health','http://www.cityofchicago.org/city/en/depts/cdph.html','',null,'','','2014-05-03 00:00:00','gsanders','2014-05-03 00:00:00','',0,0,'','chapin');

INSERT INTO data_source (data_source_abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) 
VALUES('CPD','Chicago Police Department','http://www.cityofchicago.org/city/en/depts/cpd.html','',null,'','','2014-05-03 00:00:00','gsanders','2014-05-03 00:00:00','',0,0,'','chapin');

INSERT INTO data_source (data_source_abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) 
VALUES('CPS','Chicago Public Schools','http://www.cps.edu/Pages/home.aspx','',null,'','','2014-05-03 00:00:00','gsanders','2014-05-03 00:00:00','',0,0,'','chapin');

INSERT INTO data_source (data_source_abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) 
VALUES('COOK_DPH','Cook County Department of Public Health','http://www.cookcountypublichealth.org/','',null,'','','2014-05-03 00:00:00','gsanders','2014-05-03 00:00:00','',0,0,'','chapin');

INSERT INTO data_source (data_source_abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) 
VALUES('COOK_JUVCT','Juvenile Court of Cook County','','',null,'','','2014-05-03 00:00:00','gsanders','2014-05-03 00:00:00','',0,0,'','chapin');

INSERT INTO data_source (data_source_abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) 
VALUES('IDES','Illinois Department of Employment Security','','',null,'','','2014-05-03 00:00:00','gsanders','2014-05-03 00:00:00','',0,0,'','chapin');

INSERT INTO data_source (data_source_abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) 
VALUES('IL_DCFS','Illinois Department of Children and Family Services','http://www.state.il.us/dcfs/index.shtml','',null,'','','2014-05-03 00:00:00','gsanders','2014-05-03 00:00:00','',0,0,'','chapin');

INSERT INTO data_source (data_source_abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) 
VALUES('IL_HFS','Illinois Department of Healthcare and Family Services','http://www2.illinois.gov/hfs/Pages/default.aspx','',null,'','','2014-05-03 00:00:00','gsanders','2014-05-03 00:00:00','',0,0,'','chapin');

INSERT INTO data_source (data_source_abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) 
VALUES('IL_DJJ','Illinois Department of Juvenile Justice','https://www.illinois.gov/idjj/Pages/default.aspx','',null,'','','2014-05-03 00:00:00','gsanders','2014-05-03 00:00:00','',0,0,'','chapin');

INSERT INTO data_source (data_source_abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) 
VALUES('IL_DHS','Illinois Department of Human Services','http://www.dhs.state.il.us/page.aspx?','',null,'','','2014-05-03 00:00:00','gsanders','2014-05-03 00:00:00','',0,0,'','chapin');

INSERT INTO data_source (data_source_abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) 
VALUES('IL_DPH','Illinois Department of Public Health','http://www.idph.state.il.us/','',null,'','','2014-05-03 00:00:00','gsanders','2014-05-03 00:00:00','',0,0,'','chapin');

INSERT INTO data_source (data_source_abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) 
VALUES('NSC','National Student Clearinghouse','http://www.studentclearinghouse.org/','',null,'','','2014-05-03 00:00:00','gsanders','2014-05-03 00:00:00','',0,0,'','chapin');

INSERT INTO data_source (data_source_abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) 
VALUES('GTS','GED Testing Service','http://www.gedtestingservice.com/ged-testing-service','',null,'','','2014-05-03 00:00:00','gsanders','2014-05-03 00:00:00','',0,0,'','chapin');


/*
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(1,'AIROPERATO_OPERATORS','Air Operators','null','null',null,'null','null','2012-08-03 00:00:00','gsanders', '2012-08-03 00:00:00', 'null',0,0,'null',  'cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(2,'AMERICANCO_ITYSURVEY','American Community Survey','null','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(3,'AMTRAKMONT_CEREPORTS','Amtrak Monthly Performance Reports','http://www.amtrak.com','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(4,'ANALYSISBY_ECHNOLOGY','Analysis by Center for Neighborhood Technology','http://www.cnt.org/','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(5,'BIRDCONSER_ONNETWORK','Bird Conservation Network','http://www.bcnbirds.org/trends/index.htm','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(7,'BUREAUOFLA_TATISTICS','BUREAU OF LABOR STATISTICS','HTTP://WWW.BLS.GOV','The Bureau of Labor Statistics is the principal fact-finding agency for the Federal Government in the broad field of labor economics and statistics.',null,'null','null','2012-08-03 00:00:00','gsanders','2012-11-19 00:00:00','GMS', 0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(8,'BUREAUOFTR_TATISTICS','Bureau of Transportation Statistics','http://www.bts.gov/programs/airline_information/','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(9,'CAMPAIGNMO_MONEY.COM','Campaignmoney.com','http://www.campaignmoney.com','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(10,'CENTERFORN_ECHNOLOGY','Center for Neighborhood Technology','http://www.cnt.org/','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(11,'CENTERSFOR_REVENTION','Centers for Disease Control and Prevention','http://apps.nccd.cdc.gov/ddtstrs/default.aspx','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(12,'CHICAGOCOM_NITYTRUST','Chicago Community Trust','http://cct.org','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(13,'CHICAGOMET_RPLANNING','Chicago Metropolitan Agency for Planning','http://www.cmap.illinois.gov','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(14,'CHICAGOREG_EPROGRAM)','Chicago Region Environmental and Transportation Efficiency Program (CREATE Program)','http://www.createprogram.org/index.htm','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(15,'CHICAGOREH_ABNETWORK','Chicago Rehab Network','http://www.chicagorehab.org/','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(16,'CITYOFCHIC_OFCHICAGO','City of Chicago','http://www.cityofchicago.org/city/en/depts/bldgs.html','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(17,'CLARITASRE_SRESEARCH','Claritas Research','http://www.claritas.com/sitereports/default.jsp','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(18,'CMAP:MUNIC_ONSSURVEY','CMAP: Municipal Plans Programs and Operations Survey','http://www.cmap.illinois.gov','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(19,'CMAP_CMAP','CMAP','http://www.cmap.illinois.gov/cmp/measurement','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(20,'CMAPADMINI_DSANDIDOT','CMAP administrative records and IDOT','null','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(21,'CMAPANALYS_AFROMNCCS','CMAP Analysis of US Census Bureau and IRS Business Master Files (Exempt Organizations) data from NCCS','http://nccsdataweb.urban.org','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(22,'CMAPANALYS_ESSORDATA','CMAP Analysis of County Assessor Data','http://www.cmap.illinois.gov','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(23,'CMAPANALYS_FIDOTDATA','CMAP Analysis of IDOT Data','http://www.cmap.illinois.gov/freight-committee','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(24,'CMAPANALYS_RCELFILES','CMAP Analysis of County Assessor Parcel Files','http://www.cmap.illinois.gov','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(25,'CMAPANALYS_UREAUDATA','CMAP analysis of U.S. Census Bureau data','http://www.cmap.illinois.gov','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(26,'CMAPANDUSC_DUSCENSUS','CMAP and US Census','http://www.cmap.illinois.gov','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(27,'CMAPBIKEWA_IONSYSTEM','CMAP Bikeway Information System','http://www.cmap.illinois.gov/bike-ped/soles-and-spokes-plan/documents','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(28,'CMAPLANDUS_INVENTORY','CMAP Land Use Inventory','http://www.cmap.illinois.gov','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(29,'CNTANALYSI_ITIESDATA','CNT Analysis of Utilities Data','http://www.cnt.org/','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(30,'COMPILEDBY_IMETABLES','Compiled by CMAP from carriers timetables','null','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(31,'COPYRIGHT2_RESERVED.','Copyright 2011 President and Fellows of Harvard College. All rights reserved.','www.clustermapping.us','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(32,'COUNCILFOR_CRESEARCH','Council for Community and Economic Research','http://www.c2er.org/','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(33,'COUNTYBUSI_SPATTERNS','County Business Patterns','http://www.census.gov/econ/cbp/index.html','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(34,'COUNTYBUSI_TERNS2009','County Business Patterns 2009','null','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(35,'COUNTYTAXA_ASSESSORS','County Tax Assessors','null','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(36,'CTA,METRA,_ETRA,PACE','CTA,Metra,Pace','null','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(37,'CULTURALDA_TAPROJECT','Cultural Data Project','http://www.ilculturaldata.org/','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(38,'DUNANDBRAD_RADSTREET','Dun and Bradstreet','http://www.dnbgov.com/','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(39,'EMILIAISTR_ION,2012)','Emilia Istrate and Nicholas Marchio,Export Nation 2012 (Washington,DC: Brookings Institution,2012)','http://www.brookings.edu','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(40,'FEDERALCOM_OMMISSION','Federal Communications Commission','http://hraunfoss.fcc.gov/edocs_public/','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(41,'FEDERALFIN_ONCOUNCIL','Federal Financial Institutions Examination Council','http://www.ffiec.gov','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(42,'FFIEC,CRAA_EGATEFILE','FFIEC,CRA aggregate file','http://www.ffiec.gov/','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(43,'HEALTHRESO_ISTRATION','Health Resources and Services Administration','http://muafind.hrsa.gov/','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(44,'HIGHWAYPER_INGSYSTEM','Highway Performance Monitoring System','null','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(45,'HUD/USPS_HUD/USPS','HUD/USPS','http://www.huduser.org/portal/datasets/usps.html','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(46,'IDOTDIVISI_FICSAFETY','IDOT Division of Traffic Safety','http://www.dot.state.il.us/safety.html','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(47,'IEPA_IEPA','IEPA','http://www.epa.state.il.us','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(48,'ILLINOISBE_NCESYSTEM','Illinois Behavioral Risk Factor Surveillance System','http://app.idph.state.il.us/brfss/','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(49,'ILLINOISBO_FHIGHERED','Illinois Board of Higher Ed','http://www.ibhe.state.il.us/','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(50,'ILLINOISCO_OMMISSION','Illinois Commerce Commission','null','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(51,'ILLINOISDE_ISSUANCES','Illinois Department of Human Services,Net EBT Supplemental Nutrition Assistance Program Issuances','null','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(52,'ILLINOISDE_LICHEALTH','Illinois Department of Public Health','http://app.idph.state.il.us/IPLANDataSystem.asp?menu=1','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(53,'ILLINOISDE_OFREVENUE','Illinois Department of Revenue','http://www.revenue.state.il.us/','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(54,'ILLINOISDE_PORTATION','Illinois Department of Transportation','http://www.dot.il.gov/saferoutes/SafeRoutesHome.aspx','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(55,'ILLINOISDE_TSECURITY','Illinois Department of Employment Security','http://www.ides.state.il.us/','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(56,'ILLINOISDE_YSERVICES','Illinois Department of Children and Family Services','http://www.state.il.us/dcfs/library/com_communications_zipcants.shtml','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(57,'ILLINOISEA_DASSETMAP','Illinois Early Childhood Asset Map','http://iecam.crc.uiuc.edu/','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(58,'ILLINOISEN_IONAGENCY','Illinois Environmental Protection Agency','http://www.epa.state.il.us/air/air-quality-report/','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(59,'ILLINOISEN_SUSBUREAU','Illinois Environmental Protection Agency and US Census Bureau','http://www.epa.state.il.us/land/site-remediation/site-remediation-faq.html','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(60,'ILLINOISNA_INVENTORY','Illinois Natural Areas Inventory','http://www.inhs.illinois.edu/research/inai/','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(61,'ILLINOISOF_FORCEMENT','Illinois Office of Child Support Enforcement','http://www.childsupportillinois.com/','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(62,'ILLINOISRO_IONSYSTEM','Illinois Roadway Information System','http://www.dot.state.il.us/iris/tableA.html','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(63,'ILLINOISST_ATEPOLICE','Illinois State Police','http://www.isp.state.il.us/crime/ucrhome.cfm','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(64,'ILLINOISST_EDUCATION','Illinois State Board of Education','http://www.isbe.state.il.us/','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(65,'ILLINOISST_ELECTIONS','Illinois State Board of Elections','http://www.elections.il.gov/','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(66,'ILLINOISST_SUSBUREAU','Illinois State Board of Elections and US Census Bureau','http://www.elections.il.gov/','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(67,'ILLINOISYO_UTHSURVEY','Illinois Youth Survey','http://www.illinoisyouthsurvey.org/','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(68,'INSTITUTEO_YSERVICES','Institute of Museum and library Services','http://www.imls.gov/','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(69,'INTEGRATED_EM(IPEDS)','Integrated Postsecondary Education Data System (IPEDS)','http://nces.ed.gov/ipeds/','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(70,'INTERNATIO_ADEONLINE','International Trade Administration and USA Trade Online','null','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(71,'IRSBUSINES_AFROMNCCS','IRS Business Master Files (Exempt Organizations) data from NCCS','http://nccsdataweb.urban.org','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(72,'MCICANALYS_CINCTDATA','MCIC Analysis of US Census Bureau and Voting Precinct Data','http://www.mcic.org','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(73,'METRA_METRA','Metra','www.metrarail.com','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(74,'METROSTUDY_ETROSTUDY','Metrostudy','http://www.metrostudy.com/view_market.php?id=13','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(75,'MOODYS_MOODYS','Moodys','http://www.moodys.com/','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(76,'NATIONALBR_INVENTORY','National Bridge Inventory','http://www.fhwa.dot.gov/bridge/nbi.htm','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(77,'NATIONALCE_ICS,IPEDS','National Center for Education Statistics,IPEDS','http://nces.ed.gov/ipeds/','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(78,'NATIONALCE_TATISTICS','National Center for Education Statistics','http://nces.ed.gov/ipeds/','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(79,'NATIONALRE_RICPLACES','National Register of Historic Places','http://www.nps.gov/nr/','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(80,'NATIONALSC_OUNDATION','National Science Foundation','http://www.nsf.gov/statistics/rdexpenditures/','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(81,'NATIONALTR_SEANDCMAP','National Transit Database and CMAP','http://www.ntdprogram.gov/ntdprogram/','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(82,'NATIONALTR_TDATABASE','National Transit Database','http://www.ntdprogram.gov/ntdprogram/','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(83,'NATL.CTR.F_TATISTICS','Natl.Ctr.for Charitable Statistics','http://nccs.urban.org/','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(84,'NCES,NATIO_TLITERACY','NCES,National Assessment of Adult Literacy','http://nces.ed.gov/naal/','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(85,'NIU:ILLINO_CESCENTER','NIU: Illinois Water Resources Center','http://web.extension.illinois.edu/iwrc/','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(86,'OPERATINGC_COMPANIES','Operating Companies','null','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(87,'PACE_PACE','Pace','www.pacebus.com','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(88,'PREPAREDBY_LLWAYDATA','Prepared by Chicago Metropolitan Agency for Planning Using IDOT and Illinois Tollway data','null','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(89,'QUARTERLYC_TATISTICS','Quarterly Census of Employment and Wages,Burea of Labor Statistics','http://www.bls.gov/cew/','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(90,'RAILROADSV_ATACENTER','Railroads via AAR Performance Measurement; USACE Navigation Data Center','null','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(91,'RECORDINFO_NSERVICES','Record Information Services','http://www.public-record.com','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(92,'RTAMS_RTAMS','RTAMS','http://www.rtams.org/rtams/home.jsp','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(93,'SCARBOROUG_HRESEARCH','Scarborough Research','http://www.scarborough.com/','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(94,'THECHICAGO_AUTHORITY','The Chicago Transit Authority','www.transitchicago.com','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(95,'THENATIONA_SEANDCMAP','The National Transit Database and CMAP','http://www.ntdprogram.gov/ntdprogram/data.htm','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(96,'THETAXFOUN_OUNDATION','The Tax Foundation','http://www.taxfoundation.org/publications/show/22693.html','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(97,'U.S.DEPART_RICULTURE','U.S. Department of Agriculture,Census of Agriculture','http://www.agcensus.usda.gov','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(98,'USBUREAUOF_CANALYSIS','US Bureau of Economic Analysis','http://www.bea.gov/','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(99,'USCENSUSBU_EDIVISION','US Census Bureau,Foreign Trade Division','http://www.census.gov','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(100,'USCENSUSBU_SUSBUREAU','US Census Bureau','http://www.census.gov','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(101,'USDEPARMEN_PORTATION','US Deparment of Transportation','null','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(102,'USDEPARTME_RICULTURE','US Department of Agriculture','http://www.agcensus.usda.gov/','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(103,'USDEPTOFED_ATESURVEY','US Dept of Education,Graduation Rate Survey','http://nces.ed.gov/ipeds/','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(104,'USGEOLOGIC_CALSURVEY','US Geological Survey','http://water.usgs.gov/watuse/data/2005/index.html','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(105,'USGS-WATER_TEDSTATES','USGS - Water Use in the United States','http://water.usgs.gov/watuse/','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(106,'USPATENTAN_ARKOFFICE','US Patent and Trademark Office','http://www.uspto.gov/','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(107,'USSUBSTANC_ISTRATION','US Substance Abuse and Mental Health Services Administration','http://www.oas.samhsa.gov/nsduh.htm','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
INSERT INTO data_source (ID,abbrev,data_source_name,data_source_url,description,NMFLDFORDATSRC,terms_of_use,CONTRACTS,date_created,creator,last_updated,update_user,EXCLUDE,delete_row,comments,hubid) VALUES(108,'WOODSTOCKI_INSTITUTE','Woodstock Institute','null','null',null,'null','null','2012-08-03 00:00:00','gsanders','2012-08-03 00:00:00','null',0,0,'null','cmap');
*/

SELECT * FROM data_source;
